// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Lifter",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Lifter",
            targets: ["AppModule"],
            bundleIdentifier: "com.freddie.Lifter",
            teamIdentifier: "LM36LBTR4M",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft,
            ],
            capabilities: [
                .camera(purposeString: "Required for AR Minigame")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
